name: test-prod CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 构建检查
    runs-on: ubuntu-latest

    steps:
     - name: 检出代码
       uses: actions/checkout@v4
      
     - name: 安装 node.js 22
       uses: actions/setup-node@v4
       with:
        node-version: '22'
        cache: 'npm'

     - name: "安装依赖"
       run: npm install

     - name: "构建"
       run: npm run build
       